# For more info on HTTP files go to https://aka.ms/vs/httpfile
@WebApi_HostAddress = https://localhost:5001
@AuthCookieName = .AspNetCore.Identity.Application
@AuthCookieValue = <AuthCookieValue>

# GET Identity Account Login
# Get the @RequestVerificationToken necessary for logging in.
GET {{WebApi_HostAddress}}/Identity/Account/Login

###

# POST Identity Account Login
# Get the @AuthCookieValue necessary for authenticating requests.
@Email=administrator@localhost
@Password=Administrator1!
@RequestVerificationToken=<RequestVerificationToken>
POST {{WebApi_HostAddress}}/Identity/Account/Login
Content-Type: application/x-www-form-urlencoded

Input.Email={{Email}}&Input.Password={{Password}}&__RequestVerificationToken={{RequestVerificationToken}}

###

# GET WeatherForecast
GET {{WebApi_HostAddress}}/api/WeatherForecasts
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# GET TodoLists
GET {{WebApi_HostAddress}}/api/TodoLists
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

#GET TodoList
GET {{WebApi_HostAddress}}/api/TodoLists/1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# POST TodoLists
POST {{WebApi_HostAddress}}/api/TodoLists
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{WebApi_HostAddress}}/api/TodoLists/1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{WebApi_HostAddress}}/api/TodoLists/1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{WebApi_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###

# POST TodoItems
POST {{WebApi_HostAddress}}/api/TodoItems
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{WebApi_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{WebApi_HostAddress}}/api/TodoItems/1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{WebApi_HostAddress}}/api/TodoItems/1
Cookie: {{AuthCookieName}}={{AuthCookieValue}}

###